[tool.poetry]
name = "dspro"
version = "0.1.0"
description = ""
authors = ["Linus Schlumberger <l@mll.one>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyterlab = "^4.1.2"
notebook = "^7.1.0"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
